#!/usr/bin/env bash
# Week 10: repository finalisation + the technical report, then tag v1.0.0.
set -e
R=$HOME/projects/LunarSafeMap
cd "$R"
source $HOME/miniconda3/etc/profile.d/conda.sh
conda activate lunarsafe

echo "=== 1. pre-flight ==="
python tests/test_script_index.py | tail -2
bash scripts/run_all_tests.sh | tail -2

echo
echo "=== 2. upsert derived products ==="
OUT=data/metadata/derived_products.csv
[ -f "$OUT" ] || echo "product_id,path,size_bytes,sha256,note" > "$OUT"
upsert () {
  local id="$1" path="$2" note="$3"
  if [ -f "$path" ]; then
    grep -v "^${id}," "$OUT" > "$OUT.tmp" || true
    printf "%s,%s,%s,%s,%s\n" "$id" "$path" "$(stat -c %s "$path")" \
      "$(sha256sum "$path" | cut -d" " -f1)" "$note" >> "$OUT.tmp"
    mv "$OUT.tmp" "$OUT"
    echo "  + $id"
  else
    echo "  ! missing $path (skipped)"
  fi
}
upsert Technical_report_v1 docs/LunarSafeMap_technical_report_v1.0.docx \
  "Technical report v1.0 (17 pages): methods, results, discussion, limitations, appendix"
upsert NAC_DEM_preview outputs/week4/nac_dem_preview.png \
  "Preview figure of the NAC stereo DEM (3.283 m/px)"

echo
echo "=== 3. git status ==="
git add -A
git status --short | head -30

echo
echo "=== 4. commit ==="
git commit -q \
  -m "v1.0.0: repository finalisation and technical report" \
  -m "repository hygiene" \
  -m "- LICENSE: a real MIT text (the previous file wrapped the licence in a markdown code fence)" \
  -m "- CITATION.cff: filled in (was empty) with the software metadata and the two references the work builds on" \
  -m "- pyproject.toml: filled in (was empty) with project metadata, pytest and ruff configuration; the repository is not a distributed package and this is stated in the file" \
  -m "- README_CN.md rewritten: it previously contained a week-1-era draft wrapped in a markdown fence; it now mirrors the English README and links the Chinese documentation" \
  -m "- docs/workflow.md: Mermaid overview of the full pipeline, and docs/progress_review.md (renamed from weeks1_6, now covering weeks 1-9); the stale weeks1_5 copy and the stray top-level run_lronac_quick_example.sh are gone" \
  -m "- scripts/run_all_tests.sh: runs the whole suite; it immediately found a test with a hard-coded Windows path, now fixed (5/5 tests pass)" \
  -m "- .github/workflows/ci.yml: the index-integrity test and a syntax check on every push (the scientific tests need GDAL, torch and the derived products, which are not in the repository)" \
  -m "technical report" \
  -m "- docs/LunarSafeMap_technical_report_v1.0.docx: 17 pages, generated by scripts/build_technical_report.py from the repository results (summary in Chinese and English, methods, results, discussion, six explicit limitations, transferability, and appendices with the script index and reproduction commands)" \
  -m "- seven figures embedded; alt text set on every image (the accessibility audit reports no high-severity findings)" \
  -m "- rendered with LibreOffice and reviewed page by page for blank pages and clipping (17 pages, no blank page; the report is regenerable, so it cannot drift from the analysis)" \
  || echo "(nothing to commit)"

echo
echo "=== 5. push ==="
export GIT_ASKPASS=$HOME/.git-askpass-lunarsafe.sh
unset http_proxy https_proxy
pushed=0
for attempt in 1 2 3; do
  if timeout 300 git push origin main > /tmp/lsm_w10_push.log 2>&1; then
    echo "  OK (direct, attempt $attempt)"; tail -2 /tmp/lsm_w10_push.log; pushed=1; break
  fi
  echo "  attempt $attempt failed"; tail -2 /tmp/lsm_w10_push.log; sleep 5
done
[ "$pushed" = "0" ] && echo "  ! push failed after 3 attempts"
echo "  ahead/behind: $(git rev-list --left-right --count main...origin/main)"

echo
echo "=== 6. tag v1.0.0 ==="
git tag -f v1.0.0 -m "LunarSafeMap v1.0.0: pipeline, uncertainty analysis and technical report"
if timeout 300 git push -f origin v1.0.0 2>&1 | tail -2; then echo "  tag pushed"; fi

echo
echo "=== 7. one-way backup: repo -> Windows ==="
bash scripts/backup_to_windows.sh
echo
echo "[week10-finalize] DONE"
